name: Deb Build

on:
  repository_dispatch:
  workflow_dispatch:

env:
  RELENG_HOST_ARCH: arm64
  DISTRIBUTION: bookworm
  AUTHOR_EMAIL: erdis87@gmail.com
  AUTHOR_NAME: Pisti87

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Queue
        uses: ahmadnassri/action-workflow-queue@v1
      - uses: actions/checkout@v3
      - name: Clone ${{ github.event.client_payload.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          submodules: true
          path: source
          ref: ${{ env.DISTRIBUTION }}
      - name: Build docker image
        run: |
          docker build . -t debbuild
      - name: Build packages
        run: |
          docker run --privileged -e _DEB_BUILD_TYPE="${{ github.event.client_payload.build_type }}" -e RELENG_HOST_ARCH="${{ env.RELENG_HOST_ARCH }}" -v $(pwd):/buildd -v /dev:/host-dev -v /sys/fs/cgroup:/sys/fs/cgroup -v $(pwd)/source:/buildd/sources --security-opt seccomp:unconfined debbuild
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: |
            *.deb

  publish:
    name: Publish
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apt repository
        uses: actions/checkout@v3
        with:
          ref: bookworm
          submodules: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Copy deb packages
        run: |
          mv artifacts/*/*.deb pool/main/
          rm -rf artifacts
      - name: Update and sign apt repository
        run: |
          homedir="$(pwd)"
          dpkg-scanpackages --arch arm64 pool/ > dists/bookworm/main/binary-arm64/Packages
          cat dists/bookworm/main/binary-arm64/Packages | gzip -9 > dists/bookworm/main/binary-arm64/Packages.gz
          cd dists/bookworm
          $homedir/generate-release.sh > Release
          gpg --default-key "erdist87@gmail.com" -abs -o - Release > Release.gpg
          gpg --default-key "erdist87@gmail.com" --clearsign -o - Release > InRelease
          cd $homedir
      - name: Push apt repository changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          author_name: Pisti87
          author_email: erdist87@gmail.com
          message: "Update packages"
          branch: "bookworm"
  cleanup_job:
    name: Cleanup
    needs: Publish
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Clean old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
